### ISSUE TITLE
Parameters are not consistent in StronglyConvexBoundedDomain.m

### ISSUE THREAD

**Issue by ErwanMeunier** [AdrienTaylor/Performance-Estimation-Toolbox#9]
Hello,

I think there is a typo in the file` StronglyConvexBoundedDomain.m`. In practice, the following test is performed:
`assert(D>=0 & R>=0 & L>=0,'Constants provided to the functional class are not valid')` but `L` is not given in parameters. So the assert always fails. I guess `mu` should replace `L` in this expression.

Best,
Erwan

**Comment by AdrienTaylor** [comment]
Hello,

Yes, you are perfectly right; thanks for spotting it!

Cheers,
